name: Release

on:
  workflow_run:
    workflows:
      - check-test-build
    branches:
      - main
    types:
      - completed

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    environment: npm_public
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-bun-env
      - name: Build
        run: bun run build
      - name: Verify provenance
        run: npm audit signatures
      - name: Release
        uses: ./.github/actions/semantic-release
        with:
          dry-run: "false"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}
